using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using ModelContextProtocol;
using RestSharp;
using RestSharp.Authenticators;

var builder = Host.CreateEmptyApplicationBuilder(settings: null);

builder.Services.AddMcpServer()
    .WithStdioServerTransport()
    .WithToolsFromAssembly();

// Read common configuration
var authToken = Environment.GetEnvironmentVariable("ORDER_API_TOKEN")
    ?? "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBhdmFua3VtYXJAc2VsbGVyc2NvbW1lcmNlLmNvbSIsImVtYWlsIjoicGF2YW5rdW1hckBzZWxsZXJzY29tbWVyY2UuY29tIiwibmFtZWlkIjoiYTljYjhhMjQtZGMwNS00YjI3LWIyMWEtMDM0NTVmNjVmNzYwIiwiRmlyc3ROYW1lIjoiUGF2YW4iLCJMYXN0TmFtZSI6Ikt1bWFyIiwiU2Vzc2lvbiI6IjE0NmFlMjViLTMxMjMtNDY5Zi1hMThkLTRmNjc1MTA3NzY5ZCIsIk9yaWdpbiI6Im9yZzIuZWFzeWZhc3Rub3cuY29tIiwiQXBwUmVmZXJlbmNlIjoiOWE1NjI3ZDQtNGI2Yi00OWFiLTg0MzItMjE4MzkyY2UzMmYxIiwiYXVkIjpbIkNDRGV2QWxsb2NhdGlvbkNvbW1hbmRBUEkiLCJDQ0RldkFsbG9jYXRpb25RdWVyaWVzQVBJIiwiQ0NEZXZFeHBvcnRzUXVlcmllc0FQSSIsIkNDRGV2RXhwb3J0c0NvbW1hbmRBUEkiLCJDQ0RldlF1b3RlQ29tbWFuZHNBUEkiLCJDQ0RldlF1b3RlUXVlcmllc0FQSSIsIkNDRGV2V2lzaGxpc3RBUEkiLCJDQ0RldkNhcnRRdWVyaWVzQVBJIiwiQ0NEZXZDYXJ0Q29tbWFuZHNBUEkiLCJEZXZPbmVTb3VyY2VBUEkiLCJOb2RlQ29tbW9uU2VydmljZSIsIkNDRGV2Q01TUXVlcmllc0FQSSIsIkNDRGV2Q01TQ29tbWFuZEFQSSIsIkNDRGV2QWNjb3VudENvbW1hbmRBUEkiLCJDQ0RldkFjY291dFF1ZXJpZXNBUEkiLCJDQ0RldkF1dGhTeW5jQ29tbWFuZEFQSSIsIkNDRGV2Q29yZUNvbnRyb2xDb21tYW5kQVBJIiwiQ0NEZXZDb3JlQ29udHJvbFF1ZXJpZXNBUEkiLCJDQ0RldkN1c3RvbWVyQ29tbWFuZEFQSSIsIkNDRGV2Q3VzdG9tZXJRdWVyaWVzQVBJIiwiQ0NEZXZQYXltZW50Q29uZmlnQ29tbWFuZEFQSSIsIkNDRGV2UGF5bWVudENvbmZpZ1F1ZXJpZXNBUEkiLCJDQ0RldlBNQ29tbWFuZEFQSSIsIkNDRGV2UE1RdWVyaWVzQVBJIiwiQ0NEZXZQcm9kdWN0c0NvbW1hbmRBUEkiLCJDQ0RldlJ1bGVDb21tYW5kQVBJIiwiQ0NEZXZSdWxlUXVlcmllc0FQSSIsIkNDRGV2U2FsZXNDb21tYW5kQVBJIiwiQ0NEZXZTZWFyY2hDb21tYW5kQVBJIiwiQ0NEZXZTZWFyY2hRdWVyaWVzQVBJIiwiQ0NEZXZTaGlwcGluZ0NvbW1hbmRBUEkiLCJDQ0RldlNoaXBwaW5nUXVlcmllc0FQSSIsIkNDRGV2VGF4Q29uZmlnQ29tbWFuZEFQSSIsIkNDRGV2VGF4Q29uZmlnUXVlcmllc0FQSSIsIkNDRGV2VU1RdWVyaWVzQVBJIiwiQ0NEZXZXSUNvbW1hbmRBUEkiLCJDQ0RldldJUXVlcmllc0FQSSIsIkNDRGV2V2Vic2l0ZUNvbW1hbmRBUEkiLCJDQ0RldldlYnNpdGVRdWVyaWVzQVBJIiwiQ0NEZXZNYXJrZXRpbmdDb21tYW5kQVBJIiwiQ0NEZXZNYXJrZXRpbmdRdWVyaWVzQVBJIiwiQ0NEZXZJbXBvcnRzQ29tbWFuZEFQSSIsIkNDRGV2SW1wb3J0c1F1ZXJpZXNBUEkiLCJDQ0Rldk1hY3Jvc0NvbW1hbmRBUEkiLCJDQ0Rldk1hY3Jvc1F1ZXJpZXNBUEkiLCJEZXZJbXBvcnRDb21tYW5kQVBJIiwiRGV2SW1wb3J0UXVlcmllc0FQSSIsIkNDRGV2RXZlbnRSZWdpc3RlckNvbW1hbmRBUEkiLCJDQ0Rldk9yZGVyQ29tbWFuZHNBUEkiLCJDQ0Rldk9yZGVyUXVlcmllc0FQSSJdLCJzY29wZSI6IiIsIm5iZiI6MTc2MzM5MDE2MywiZXhwIjoxNzYzNDc2NTYzLCJpYXQiOjE3NjMzOTAxNjMsImlzcyI6ImVkZ2UtZGV2LWlzc3VlciJ9.gKE-6M_mbZOjFs2OfIn2ewE_ihIfBXYse1b84XZhXuX410vs6dttAXpbP4q45VWKWZci4NVc53NzIYjB6O9J-Rrwj6HdKTEZM13QMyAibS8fHstkl9EcCjW5aNuuIzVGxVbDv7QdHn6gdHU8FZ92lTbzq6ZnCy0Ap5_Q5AaZjp2q31Cyr8dQJ9_P3oBQF_DJSgID1BtF8DhY6zRFzpq8IuJEyNsdOgdqAY7TavvdhBiPye_B-m7V9Dtp1loEcLa41rCfS919_I6H6-ktDMSuqxtK7AepVch1TwiZGYXqiZ-IGwEbLj3sn55hz6wpkGKnjbW9wTIt30D8MwHl6-f-wA\",\"refreshToken\":\"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJjNzllNWM1MC02YmUzLTRhZGYtYTcwNy01MDdlYjQyMGRkYmYiLCJUZW5hbnRJZCI6IjEiLCJTZXNzaW9uIjoiMTQ2YWUyNWItMzEyMy00NjlmLWExOGQtNGY2NzUxMDc3NjlkIiwibmJmIjoxNzYzMzkwMTYzLCJleHAiOjE3NjM0MjYxNjMsImlhdCI6MTc2MzM5MDE2MywiaXNzIjoiZWRnZS1kZXYtaXNzdWVyIiwiYXVkIjoiQ0NEZXZBY2NvdW50Q29tbWFuZEFQSSBDQ0RldkFjY291dFF1ZXJpZXNBUEkgQ0NEZXZBdXRoU3luY0NvbW1hbmRBUEkgQ0NEZXZDb3JlQ29udHJvbENvbW1hbmRBUEkgQ0NEZXZDb3JlQ29udHJvbFF1ZXJpZXNBUEkgQ0NEZXZDdXN0b21lckNvbW1hbmRBUEkgQ0NEZXZDdXN0b21lclF1ZXJpZXNBUEkgQ0NEZXZQYXltZW50Q29uZmlnQ29tbWFuZEFQSSBDQ0RldlBheW1lbnRDb25maWdRdWVyaWVzQVBJIENDRGV2UE1Db21tYW5kQVBJIENDRGV2UE1RdWVyaWVzQVBJIENDRGV2UHJvZHVjdHNDb21tYW5kQVBJIENDRGV2UnVsZUNvbW1hbmRBUEkgQ0NEZXZSdWxlUXVlcmllc0FQSSBDQ0RldlNhbGVzQ29tbWFuZEFQSSBDQ0RldlNlYXJjaENvbW1hbmRBUEkgQ0NEZXZTZWFyY2hRdWVyaWVzQVBJIENDRGV2U2hpcHBpbmdDb21tYW5kQVBJIENDRGV2U2hpcHBpbmdRdWVyaWVzQVBJIENDRGV2VGF4Q29uZmlnQ29tbWFuZEFQSSBDQ0RldlRheENvbmZpZ1F1ZXJpZXNBUEkgQ0NEZXZVTVF1ZXJpZXNBUEkgQ0NEZXZXSUNvbW1hbmRBUEkgQ0NEZXZXSVF1ZXJpZXNBUEkgQ0NEZXZXZWJzaXRlQ29tbWFuZEFQSSBDQ0RldldlYnNpdGVRdWVyaWVzQVBJIENDRGV2TWFya2V0aW5nQ29tbWFuZEFQSSBDQ0Rldk1hcmtldGluZ1F1ZXJpZXNBUEkgQ0NEZXZJbXBvcnRzQ29tbWFuZEFQSSBDQ0RldkltcG9ydHNRdWVyaWVzQVBJIENDRGV2TWFjcm9zQ29tbWFuZEFQSSBDQ0Rldk1hY3Jvc1F1ZXJpZXNBUEkgQ0NEZXZDTVNDb21tYW5kQVBJIENDRGV2Q01TUXVlcmllc0FQSSBDQ0RldkV2ZW50UmVnaXN0ZXJDb21tYW5kQVBJIERldk9uZVNvdXJjZUFQSSBOb2RlQ29tbW9uU2VydmljZSBDQ0RldkNNU0NvbW1hbmRBUEkgQ0NEZXZFeHBvcnRzQ29tbWFuZEFQSSBDQ0RldkV4cG9ydHNRdWVyaWVzQVBJIERldkltcG9ydENvbW1hbmRBUEkgRGV2SW1wb3J0UXVlcmllc0FQSSBDQ0RldkNhcnRRdWVyaWVzQVBJIENDRGV2UXVvdGVRdWVyaWVzQVBJIENDRGV2T3JkZXJRdWVyaWVzQVBJIENDRGV2V2lzaGxpc3RBUEkgQ0NEZXZDYXJ0Q29tbWFuZHNBUEkgQ0NEZXZRdW90ZUNvbW1hbmRzQVBJIENDRGV2T3JkZXJDb21tYW5kc0FQSSBDQ0RldkF0dHJpYnV0ZVF1ZXJpZXNBUEkgQ0NEZXZBbGxvY2F0aW9uUXVlcmllc0FQSSBDQ0RldkFsbG9jYXRpb25Db21tYW5kQVBJIn0.NktVbjbFn340RjYYPkJTPNH88E1jv18hvkabgzQSgQW2633R6kLXJ4zTRkgoljDQw-cJWDkTCz4s99DZq1cJ6aBfpxnrQ6d9us1RR8W8zOeFo8tUDpsJuCeaqbAQNcFuMnEi1_20Rm9HMF8cw5ga-_IU5JOlodLN1bP4Q7BYT3dHUYJ5PjwrNWMsqaooCPqDIITqh9RTOtqjruOHpPNUyntEqsnmCJw63272_mdzzbuBgOVf0BFb7PpNM_30vDxUCqZBsRBs_LrhriKTDYc7bEXphYXdxLxX9qV7VLw3KqCAQhewM0v80bjZaqJzOLiQgWBs1N7m9y2x-obEBf9D5g";
var originUrl = Environment.GetEnvironmentVariable("ORDER_ORIGIN_URL") 
    ?? "https://org2.easyfastnow.com";

// Register RestClient for Order Queries API
builder.Services.AddKeyedSingleton("OrderQueriesClient", (sp, key) =>
{
    var baseUrl = Environment.GetEnvironmentVariable("ORDER_QUERIES_API_BASE_URL") 
        ?? "https://orders-queryservice.easyfastnow.com";

    var options = new RestClientOptions(baseUrl)
    {
        Authenticator = new JwtAuthenticator(authToken)
    };

    var client = new RestClient(options);
    client.AddDefaultHeader("User-Agent", "order-tool/1.0");
    client.AddDefaultHeader("X-Origin-Url", originUrl);
    
    return client;
});

// Register RestClient for Order Commands API
builder.Services.AddKeyedSingleton("OrderCommandsClient", (sp, key) =>
{
    var baseUrl = Environment.GetEnvironmentVariable("ORDER_COMMANDS_API_BASE_URL") 
        ?? "https://orders-commandservice.easyfastnow.com";

    var options = new RestClientOptions(baseUrl)
    {
        Authenticator = new JwtAuthenticator(authToken)
    };

    var client = new RestClient(options);
    client.AddDefaultHeader("User-Agent", "order-tool/1.0");
    client.AddDefaultHeader("X-Origin-Url", originUrl);
    
    return client;
});

// Keep the default singleton for backward compatibility (points to Queries)
builder.Services.AddSingleton(sp => sp.GetRequiredKeyedService<RestClient>("OrderQueriesClient"));

var app = builder.Build();

await app.RunAsync();
